[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
os_pipe = "1.2.3"
rustyline = { version = "17.0.1", default-features = true, features = ["with-file-history","derive"] }
